// Package encrypt wraps filippo.io/age for transparent decryption of
// age-encrypted dotfiles during compilation.
package encrypt

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"filippo.io/age"
	"filippo.io/age/armor"
)

// KeySource describes how to resolve the decryption identity.
// IdentityFile is required; Decrypt returns an error if it is empty.
type KeySource struct {
	// IdentityFile is the path to an age identity file (generated by age-keygen).
	IdentityFile string
}

// Decrypt reads age-encrypted data from src and returns the plaintext.
// It resolves the decryption identity from ks.IdentityFile.
func Decrypt(_ context.Context, src io.Reader, ks KeySource) ([]byte, error) {
	identities, err := resolveIdentities(ks)
	if err != nil {
		return nil, err
	}

	armorReader := armor.NewReader(src)
	r, err := age.Decrypt(armorReader, identities...)
	if err != nil {
		return nil, fmt.Errorf("decrypt: %w", err)
	}

	out, err := ioReadAllFunc(r)
	if err != nil {
		return nil, fmt.Errorf("decrypt: read plaintext: %w", err)
	}
	return out, nil
}

// DecryptFile reads and decrypts the age-encrypted file at path, returning the
// plaintext bytes.
func DecryptFile(ctx context.Context, path string, ks KeySource) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("decrypt file %s: %w", path, err)
	}
	defer f.Close() //nolint:errcheck // best-effort close on read-only file

	out, err := Decrypt(ctx, f, ks)
	if err != nil {
		return nil, fmt.Errorf("decrypt file %s: %w", path, err)
	}
	return out, nil
}

// resolveIdentities returns age identities for decryption from ks.
func resolveIdentities(ks KeySource) ([]age.Identity, error) {
	if ks.IdentityFile != "" {
		return loadIdentityFile(ks.IdentityFile)
	}
	return nil, errors.New(
		"no age identity file configured — set age.identity_file in .dotsmith.yml or pass --age-identity",
	)
}

// loadIdentityFile parses an age identity file.
func loadIdentityFile(path string) ([]age.Identity, error) {
	expanded := expandHome(path)
	f, err := os.Open(expanded)
	if err != nil {
		return nil, fmt.Errorf("open identity file %s: %w", path, err)
	}
	defer f.Close() //nolint:errcheck // best-effort close on read-only file

	ids, err := age.ParseIdentities(f)
	if err != nil {
		return nil, fmt.Errorf("parse identity file %s: %w", path, err)
	}
	return ids, nil
}

// Injectable functions for testing error paths.
var (
	userHomeDirFunc = os.UserHomeDir
	ioReadAllFunc   = io.ReadAll
)

// expandHome replaces a leading ~ with the user's home directory.
func expandHome(path string) string {
	if !strings.HasPrefix(path, "~/") {
		return path
	}
	home, err := userHomeDirFunc()
	if err != nil {
		return path
	}
	return filepath.Join(home, path[2:])
}
