// Package encrypt wraps filippo.io/age for transparent encryption and
// decryption of dotfiles during compilation.
package encrypt

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"filippo.io/age"
	"filippo.io/age/armor"
)

// KeySource describes how to resolve the encryption/decryption identity.
// IdentityFile is required; Decrypt and Encrypt return an error if it is empty.
type KeySource struct {
	// IdentityFile is the path to an age identity file (generated by age-keygen).
	IdentityFile string
}

// Decrypt reads age-encrypted data from src and returns the plaintext.
// It resolves the decryption identity from ks.IdentityFile.
func Decrypt(_ context.Context, src io.Reader, ks KeySource) ([]byte, error) {
	identities, err := resolveIdentities(ks)
	if err != nil {
		return nil, err
	}

	armorReader := armor.NewReader(src)
	r, err := age.Decrypt(armorReader, identities...)
	if err != nil {
		return nil, fmt.Errorf("decrypt: %w", err)
	}

	out, err := ioReadAllFunc(r)
	if err != nil {
		return nil, fmt.Errorf("decrypt: read plaintext: %w", err)
	}
	return out, nil
}

// Encrypt encrypts plaintext from src and writes armored age ciphertext to dst.
// It resolves the recipient from ks.
func Encrypt(_ context.Context, plaintext io.Reader, dst io.Writer, ks KeySource) error {
	recipients, err := resolveRecipients(ks)
	if err != nil {
		return err
	}

	armorWriter := armor.NewWriter(dst)
	w, err := ageEncryptFunc(armorWriter, recipients...)
	if err != nil {
		return fmt.Errorf("encrypt: create age writer: %w", err)
	}

	if _, err = io.Copy(w, plaintext); err != nil {
		return fmt.Errorf("encrypt: write plaintext: %w", err)
	}
	if err = w.Close(); err != nil {
		return fmt.Errorf("encrypt: finalize age stream: %w", err)
	}
	if err = armorWriter.Close(); err != nil {
		return fmt.Errorf("encrypt: finalize armor: %w", err)
	}
	return nil
}

// DecryptFile reads and decrypts the age-encrypted file at path, returning the
// plaintext bytes.
func DecryptFile(ctx context.Context, path string, ks KeySource) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("decrypt file %s: %w", path, err)
	}
	defer f.Close() //nolint:errcheck // best-effort close on read-only file

	out, err := Decrypt(ctx, f, ks)
	if err != nil {
		return nil, fmt.Errorf("decrypt file %s: %w", path, err)
	}
	return out, nil
}

// EncryptFileInPlace encrypts the file at path and writes the ciphertext to
// path+".age". The original file is removed only on success.
// Returns an error if path already has a ".age" extension.
func EncryptFileInPlace(ctx context.Context, path string, ks KeySource) error {
	if strings.HasSuffix(path, ".age") {
		return fmt.Errorf(
			"encrypt file %s: file already has .age extension — run 'dotsmith decrypt' first if needed",
			path,
		)
	}

	outPath := path + ".age"
	if _, err := os.Stat(outPath); err == nil {
		return fmt.Errorf(
			"encrypt file %s: output %s already exists — remove it manually before re-encrypting",
			path, outPath,
		)
	}

	plaintext, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("encrypt file %s: read plaintext: %w", path, err)
	}

	var buf bytes.Buffer
	if err = Encrypt(ctx, bytes.NewReader(plaintext), &buf, ks); err != nil {
		return fmt.Errorf("encrypt file %s: %w", path, err)
	}

	if err = os.WriteFile(outPath, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("encrypt file %s: write %s: %w", path, outPath, err)
	}

	if err = osRemoveFunc(path); err != nil {
		// Clean up the output file if original removal fails.
		_ = osRemoveFunc(outPath)
		return fmt.Errorf("encrypt file %s: remove original: %w", path, err)
	}

	return nil
}

// resolveIdentities returns age identities for decryption from ks.
func resolveIdentities(ks KeySource) ([]age.Identity, error) {
	if ks.IdentityFile != "" {
		return loadIdentityFile(ks.IdentityFile)
	}
	return nil, errors.New(
		"no age identity file configured — set age.identity_file in .dotsmith.yml or pass --age-identity",
	)
}

// resolveRecipients returns age recipients for encryption from ks.
func resolveRecipients(ks KeySource) ([]age.Recipient, error) {
	if ks.IdentityFile != "" {
		ids, err := loadIdentityFile(ks.IdentityFile)
		if err != nil {
			return nil, err
		}
		recipients := make([]age.Recipient, 0, len(ids))
		for _, id := range ids {
			// age.ParseIdentities only produces X25519Identity values.
			x := id.(*age.X25519Identity)
			recipients = append(recipients, x.Recipient())
		}
		return recipients, nil
	}
	return nil, errors.New(
		"no age identity file configured — set age.identity_file in .dotsmith.yml or pass --age-identity",
	)
}

// loadIdentityFile parses an age identity file.
func loadIdentityFile(path string) ([]age.Identity, error) {
	expanded := expandHome(path)
	f, err := os.Open(expanded)
	if err != nil {
		return nil, fmt.Errorf("open identity file %s: %w", path, err)
	}
	defer f.Close() //nolint:errcheck // best-effort close on read-only file

	ids, err := age.ParseIdentities(f)
	if err != nil {
		return nil, fmt.Errorf("parse identity file %s: %w", path, err)
	}
	return ids, nil
}

// Injectable functions for testing error paths.
var (
	userHomeDirFunc = os.UserHomeDir
	osRemoveFunc    = os.Remove
	ageEncryptFunc  = age.Encrypt
	ioReadAllFunc   = io.ReadAll
)

// expandHome replaces a leading ~ with the user's home directory.
func expandHome(path string) string {
	if !strings.HasPrefix(path, "~/") {
		return path
	}
	home, err := userHomeDirFunc()
	if err != nil {
		return path
	}
	return filepath.Join(home, path[2:])
}
